// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxWjB1OsQZE9t7a1Yqq0SW3Vj8844k4Rc',
    appId: '1:528246536527:web:f11e1dcc8919ac823cad3a',
    messagingSenderId: '528246536527',
    projectId: 'learningapp-c13b6',
    authDomain: 'learningapp-c13b6.firebaseapp.com',
    storageBucket: 'learningapp-c13b6.appspot.com',
    measurementId: 'G-J7X59PZWE3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDdq1wFxf4gK_JD-wDTKcHb-6tp8z2urc',
    appId: '1:528246536527:android:a594270b93794c493cad3a',
    messagingSenderId: '528246536527',
    projectId: 'learningapp-c13b6',
    storageBucket: 'learningapp-c13b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBY403ky4z-HDbNY28KOWmrVKn0RLiozuk',
    appId: '1:528246536527:ios:4c6d71128957c0f83cad3a',
    messagingSenderId: '528246536527',
    projectId: 'learningapp-c13b6',
    storageBucket: 'learningapp-c13b6.appspot.com',
    iosBundleId: 'com.example.codingaja',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBY403ky4z-HDbNY28KOWmrVKn0RLiozuk',
    appId: '1:528246536527:ios:4c6d71128957c0f83cad3a',
    messagingSenderId: '528246536527',
    projectId: 'learningapp-c13b6',
    storageBucket: 'learningapp-c13b6.appspot.com',
    iosBundleId: 'com.example.codingaja',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxWjB1OsQZE9t7a1Yqq0SW3Vj8844k4Rc',
    appId: '1:528246536527:web:094e37fe6d019f3e3cad3a',
    messagingSenderId: '528246536527',
    projectId: 'learningapp-c13b6',
    authDomain: 'learningapp-c13b6.firebaseapp.com',
    storageBucket: 'learningapp-c13b6.appspot.com',
    measurementId: 'G-SVSCQQ7DZQ',
  );
}
